name: ETL Pipeline demo

on:
  push:
   branches:
   - main

jobs:
  extract-data:
     runs-on: ubuntu-latest
     steps:
        - name: checkout code
          uses: actions/checkout@v2

        - name: run extract.py
          run: python scripts/extract.py

  tranform-data:
    runs-on: ubuntu-latest
    needs: extract-data
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: run transform.py
        run: python scrpits\transform.py

  load-data:
    runs-on: ubuntu-latest
    needs: tranform-data
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: run load.py
        run: python scripts\load.py
