name: ETL Pipeline demo

on:
  push:
    branches:
      - main

jobs:
  extract-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
       
      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'


      - name: show python version
        run: python --version

      - name: Run extract.py
        run: python .github/workflows/extract.py

  transform-data:
    runs-on: ubuntu-latest
    needs: extract-data
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run transform.py
        run: python .github/workflows/transform.py

  load-data:
    runs-on: ubuntu-latest
    needs: transform-data
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run load.py
        run: python .github/workflows/load.py
