name: ETL Pipeline demo

on:
  push:
   branches:
   - main

jobs:
  extract-data:
     runs-on: ubuntu-latest
     steps:
        - name: checkout code
          uses: actions/checkout@v2

        - name: run extract.py
          run: python D:\git example\githubactiondemo4\.github\workflows/extract.py

  tranform-data:
    runs-on: ubuntu-latest
    needs: extract-data
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: run transform.py
        run: python D:\git example\githubactiondemo4\.github\workflows/transform.py

  load-data:
    runs-on: ubuntu-latest
    needs: tranform-data
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: run load.py
        run: python D:\git example\githubactiondemo4\.github\workflows/load.py
